/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ReferralCodeService } from "../referralCode.service";
import { ReferralCodeCreateInput } from "./ReferralCodeCreateInput";
import { ReferralCode } from "./ReferralCode";
import { ReferralCodeFindManyArgs } from "./ReferralCodeFindManyArgs";
import { ReferralCodeWhereUniqueInput } from "./ReferralCodeWhereUniqueInput";
import { ReferralCodeUpdateInput } from "./ReferralCodeUpdateInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

export class ReferralCodeControllerBase {
  constructor(protected readonly service: ReferralCodeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ReferralCode })
  async createReferralCode(
    @common.Body() data: ReferralCodeCreateInput
  ): Promise<ReferralCode> {
    return await this.service.createReferralCode({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        code: true,
        expirationDate: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ReferralCode] })
  @ApiNestedQuery(ReferralCodeFindManyArgs)
  async referralCodes(@common.Req() request: Request): Promise<ReferralCode[]> {
    const args = plainToClass(ReferralCodeFindManyArgs, request.query);
    return this.service.referralCodes({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        code: true,
        expirationDate: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ReferralCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async referralCode(
    @common.Param() params: ReferralCodeWhereUniqueInput
  ): Promise<ReferralCode | null> {
    const result = await this.service.referralCode({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        code: true,
        expirationDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ReferralCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateReferralCode(
    @common.Param() params: ReferralCodeWhereUniqueInput,
    @common.Body() data: ReferralCodeUpdateInput
  ): Promise<ReferralCode | null> {
    try {
      return await this.service.updateReferralCode({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          code: true,
          expirationDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ReferralCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteReferralCode(
    @common.Param() params: ReferralCodeWhereUniqueInput
  ): Promise<ReferralCode | null> {
    try {
      return await this.service.deleteReferralCode({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          code: true,
          expirationDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: ReferralCodeWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstName: true,
        lastName: true,
        username: true,
        email: true,
        roles: true,
        referredBy: true,

        referralCode: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  async connectUsers(
    @common.Param() params: ReferralCodeWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updateReferralCode({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  async updateUsers(
    @common.Param() params: ReferralCodeWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updateReferralCode({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  async disconnectUsers(
    @common.Param() params: ReferralCodeWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updateReferralCode({
      where: params,
      data,
      select: { id: true },
    });
  }
}
